[package]
name = "crunch"
version = "0.1.18"
authors = ["Paulo <paulo@turboflakes.com>"]
description = "Crunch is a command-line interface (CLI) to claim staking rewards (flakes) every X hours for Substrate-based chains" 
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
envy = "0.4"
log = "0.4"
env_logger = "0.6"
clap = "2.33"
lazy_static = "1.4"
derive_more = "0.99"
async-std = { version = "1.9.0", features = ["attributes", "tokio1"] }
async-recursion = "0.3.2"
serde = "1"
thiserror = "^1.0.24"
chrono = "0.4"
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive", "full"] }
regex = "1.4.6"
reqwest = { version = "0.11", features = ["json"] }
url = "2.2.2"
base64 = "0.13.0"
percent-encoding = "2.1.0"
hex-literal = "0.3.3"
rand = "0.8.4"
substrate-subxt = { git = "https://github.com/turboflakes/substrate-subxt", rev = "9fa6fe5" }
