[package]
name = "crunch"
version = "0.3.0"
authors = ["Paulo <paulo@turboflakes.com>"]
description = "Crunch is a command-line interface (CLI) to claim staking rewards (flakes) every X hours for Substrate-based chains" 
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
envy = "0.4"
log = "0.4"
env_logger = "0.6"
clap = "2.33"
lazy_static = "1.4"
derive_more = "0.99"
async-std = { version = "1.9.0", features = ["attributes", "tokio1"] }
async-recursion = "0.3.2"
serde = "1"
serde_json = "1.0.68"
thiserror = "^1.0.24"
chrono = "0.4"
regex = "1.4.6"
reqwest = { version = "0.11", features = ["json"] }
url = "2.2.2"
base64 = "0.13.0"
rand = "0.8.4"

subxt = { package = "subxt", path = "/Users/paulo/Development/github.com/turboflakes/substrate-subxt/" }

# Dependencies required since the changes on the new subxt package

codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full"] }
frame-metadata = "14.0.0"

# codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full", "bit-vec"] }
# sp-arithmetic = { package = "sp-arithmetic", git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
# sp-core = { package = "sp-core", git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
# sp-keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.12" }
# sp-runtime = { package = "sp-runtime", git = "https://github.com/paritytech/substrate/", branch = "polkadot-v0.9.11" }


